### ISSUE TITLE
Force stop applications : "only works when the screen is on and unlocked"

### ISSUE THREAD

**Issue by rockandska** [henrichg/PhoneProfilesPlusExtender#1]
Hi there,

I just installed your application to see if it feeds my needs and just saw the apps can't be force closed if the screen is off or locked.

Is it an android limitation ?
it will be nice if PholeProfilesPlus could force to close apps even with the screen is off/locked when using a scheduler.

Regards

**Comment by henrichg** [comment]
For "Force close applications" is used Accessibility service. This service opens "App info" screen and click to "Force close" button. And this requires unlocked device screen.
Another soultion? Maybe via root.

**Comment by rockandska** [comment]
Maybe i've mistaken your answer, and i'm not an android developer, so maybe i've mistaken too some parts of the article bellow, but it seems possible to do some background tasks even in "doze" mode without root access isn't it ?
https://developer.android.com/training/scheduling/alarms#doze-and-standby 
And kill a process seem to doesn't require root too:
https://developer.android.com/reference/android/os/Process.html#killProcess(int)

Apart of this, PhoneProfilesPlus seems very nice :+1:  and i need to test it more.

Regards

**Comment by henrichg** [comment]
Accessibility service is not restricted by Doze mode.
Accessibility service is used by PPP for simulation of click to "Force close" button in "App info" screen.
When lockscreen is displayed, "App info" and it's "Force close" button is hidden by lockscreen. And for this, button is not clickable.

killProcess:
"Kill the process with the given PID. Note that, though this API allows us to request to kill any process based on its PID, the kernel will still impose standard restrictions on which PIDs you are actually able to kill. **Typically this means only the process running the caller's packages/application and any additional processes created by that app; packages sharing a common UID will also be able to kill each other's processes.**"
External application is not PPP process. Result: it is not possible to kill it via this killProcess() function. This is also tested by me.

**Comment by rockandska** [comment]
Would it be possible to kill other process on rooted devices ?
If yes, it will be handsome to add this option to rooted devices and let the actual behavior for non rooted devices.

regards,

**Comment by henrichg** [comment]
Hm, it is possible to run command `adb shell am force-stop <package_name>`, but this not kill application, when are enabled Notification access service, Accessibility service and so on.
Application is stopped but started by these services again.
Get process names of all processes running by application is another problem. It is not possible. And proccess name is required for kill application and it's services by "kill" command.
:-(
