### ISSUE TITLE
Force stop not working

### ISSUE THREAD

**Issue by rscs** [henrichg/PhoneProfilesPlusExtender#12]
The "Force stop applications" feature hasn't been working for me for a while -- probably a year or more.  I figured it was time to report it :).

The "App Info" screen will come up, but it appears PPPE is not able to simulate a click on the "Force Stop" button like it used to.

I have a Pixel 9 Pro now and it also didn't work on my Pixel 7 Pro when I had it.

I'm currently running v9.0 (910) of PPPE and v7.0 (7200) of PPP, but this feature has been broken for several versions back.

I have enabled Accessibility Service access.

I am currently on Android 15, but this feature has been broken for several versions back of Android too.

I tried changing which app I want to force stop just to see if it was app specific and the problem persists no matter which app I chose to stop.

Thank you for all you do.  This is such a useful tool!

**Comment by henrichg** [comment]
Hm.

In Galaxy S23, Android 14, working. In Pixel 6, Android 15, not working.

Maybe problem is Pixel. I will investigate it.

Dňa pi 13. 12. 2024, 23:17 Ryan S ***@***.***> napísal(a):

**Comment by henrichg** [comment]
Tested Pixel 3a, Android 12 and working.
Then, maybe problem is with Android 13-15? Hm.

**Comment by henrichg** [comment]
Hm not good:

In Pixel exists this:
-------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@19b117; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(708, 950 - 1038, 1177); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.view.View; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_FOCUS, ACTION_ACCESSIBILITY_FOCUS, ACTION_CLICK]
--------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@19b1b2; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(782, 1077 - 965, 1124); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.widget.TextView; text: Force stop; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_ACCESSIBILITY_FOCUS, ACTION_SET_SELECTION]
--------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@37d82717; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(708, 950 - 1038, 1177); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.widget.Button; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_ACCESSIBILITY_FOCUS]

But is not possible to detect it. Is not set view id for this, only "text". And problem with text is localization. :-(

**Comment by henrichg** [comment]
In Slovak language:

-------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@293813; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(708, 950 - 1038, 1230); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.view.View; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: false; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_ACCESSIBILITY_FOCUS]
--------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@2938ae; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(719, 1077 - 1027, 1177); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.widget.TextView; **text: Vynútiť zastavenie**; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_ACCESSIBILITY_FOCUS, ACTION_SET_SELECTION]
--------androidx.core.view.accessibility.AccessibilityNodeInfoCompat@37e7ae13; boundsInParent: Rect(0, 0 - 0, 0); boundsInScreen: Rect(708, 950 - 1038, 1230); boundsInWindow: Rect(0, 0 - 0, 0); packageName: com.android.settings; className: android.widget.Button; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: null; uniqueId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; containerTitle: null; granularScrollingSupported: false; importantForAccessibility: true; visible: true; isTextSelectable: false; accessibilityDataSensitive: false; [ACTION_ACCESSIBILITY_FOCUS]

**Comment by henrichg** [comment]
There is another solution that doesn't need PPP but does need root (or Shizuku, I need to test it):
"adb shell am force-stop com.google.android.calculator"

**Comment by henrichg** [comment]
Added is option to force stop with root/Shizuku. Parameter "Force stop applications" is changed to list with 2 options. For root/Shizuku is "(Z)(R) Force stop with command".

If you want, install and test it:
https://drive.google.com/file/d/1dNvsCVxH_1Tlc5uFvQoA-Qm29j60ahFl/view?usp=drivesdk

**Comment by henrichg** [comment]
Soon will be released new PPP version (7.0.1), with root/Shizuku option for Force stop apps.
