### ISSUE TITLE
F-Droid Repository

### ISSUE THREAD

**Issue by ralle666** [henrichg/PhoneProfilesPlusExtender#4]
Hi!
Would be nice if you could add it to the IzzyOnDroid F-Droid Repo.
So it would be a lot easyer to update it.
Thank you very much!

**Comment by henrichg** [comment]
Hm, yes, will be good.
But problem is with PPP. In it is all about download from GitHub. For example, PPP check Extender version and, when user has installed old version, is noted to download latest apk from GitHub. :-(
Is not possible to check download source of Extender.

**Comment by henrichg** [comment]
OK I'm changed download and installation.

Dialog "Install PhoneProfilesPLusExtender" is changed. "Install" button directly downloads required version of apk. User must then only click browser notification after download success and this invoke installation of apk. Is this better?

Extender is not normal application. For this, is better to not add it to F-Droid.

**Comment by ralle666** [comment]
I think it is a lot easier for people. Thank you very much.

**Comment by KjmT6459** [comment]
I agree that Extender should be on F-Droid. It is easier and more intuitive to provide updates through a "store" than an individual Github.

If you require an example of other apps doing this, look at MAXS. There is MAXS Main and all add-ons are listed as Modules.

The friction (confusion) of having two apps in F-Droid, if named as PPP and PPPE, as they already are, will be nearly nonexistent. As it is, the friction of how you implement it now, got me to come to your Github to suggest this very thing. And your refusal to do it means I'm going to uninstall and use a different app. Hopefully you'll change your mind in time.

**Comment by henrichg** [comment]
PPP:
1. PPP generates notification, when is needed never version od Extender. Currently is needed version 6.1.2.
2. Download and installation of Extender Is, by me, simple. Click to notification downloads it. User then must click to notification with downloaded apk to install it (standard system installation of apk from third-party sources).

F-Droid:
1. F-Droid also generates notification about new version.
2. Click it opens F-Droid and user must click "Install" button, which only downloads apk.3. User must then install apk (standard system installation of apk from third-party sources).

But is not problem add Extender to F-Droid.

**Comment by henrichg** [comment]
"OK, I will change it to by better. Will be generated notification about new Extender version and click opens Extender installation dialog."
Impleneted. Will be in next release of PhoneProiflesPlus.
