### ISSUE TITLE
Bank app not like extender permissions

### ISSUE THREAD

**Issue by userx77** [henrichg/PhoneProfilesPlusExtender#9]
Nordea Bank app reports extender app is malware and bank will not work if extender not removed from the device.

**Comment by henrichg** [comment]
Hm, this is not good. Extender requires Accessibility service for:
1. Get foreground application
2. Force stop ppllication

By me Accessibility service is problem for your bank app.

Which profile parameters/event sensors are you using, what do the Extenders require?

Thanks.

**Comment by userx77** [comment]
Extender is no longer necessary for me so I can manage without it. But maybe this was good to bring to your attention. 👍🏻

3. kesäk. 2024 klo 16.19 - lähettäjä ***@***.***:

**Comment by henrichg** [comment]
Yes, I am aware of this problem. My bank app has not problem with Extender. But yes, there are some apps that have a problem with it.
